### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by GorlemZ** [1746104160/flask-restx-marshmallow#1]
installing the package as suggested result in dependency build failure. Seems like it depends by two env var for mysql client. I'm not using mysql.....

I'll paste the output:
`
Requirement already satisfied: flask-restx<2.0.0,>=1.1.0 in /Users/myuser/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from flask-restx-marshmallow) (1.2.0)
Collecting marshmallow<4.0.0,>=3.19.0 (from flask-restx-marshmallow)
  Obtaining dependency information for marshmallow<4.0.0,>=3.19.0 from https://files.pythonhosted.org/packages/ed/3c/cebfdcad015240014ff08b883d1c0c427f2ba45ae8c6572851b6ef136cad/marshmallow-3.20.1-py3-none-any.whl.metadata
  Downloading marshmallow-3.20.1-py3-none-any.whl.metadata (7.8 kB)
Collecting marshmallow-sqlalchemy<0.30.0,>=0.29.0 (from flask-restx-marshmallow)
  Downloading marshmallow_sqlalchemy-0.29.0-py2.py3-none-any.whl (16 kB)
Collecting mysqlclient<3.0.0,>=2.1.1 (from flask-restx-marshmallow)
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/Users/myuser/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/myuser/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/myuser/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fx/4n7zrjcn0ng53w2cl_t87vp80000gn/T/pip-build-env-aifih5jw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fx/4n7zrjcn0ng53w2cl_t87vp80000gn/T/pip-build-env-aifih5jw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fx/4n7zrjcn0ng53w2cl_t87vp80000gn/T/pip-build-env-aifih5jw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

**Comment by 1746104160** [comment]
I'm so sorry to hear that. The package of this repository has only been tested on Windows and Linux platforms. The package `mysqlclient`, as an optional dependency(in [pyroject.toml](https://github.com/1746104160/flask-restx-marshmallow/blob/master/pyproject.toml)) will not be installed automatically on Windows and Linux platforms. Maybe you can try `pip install flask-restx-marshmallow[pgsql]` or `pip install flask-restx-marshmallow[pandas]`. Since I don't have a macOS computer, the above solution is for reference only.

**Comment by GorlemZ** [comment]
I've tried adding to my pyproject.toml the following line:
`flask-restx-marshmallow={extras= ["pgsql"], version="^0.1.1"}`
Unfortunately, it fails with:

` • Installing psycopg2-binary (2.9.9): Failed
[...]
Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2-binary (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psycopg2-binary (==2.9.9)"'.
`

Note that I'm not using psycopg2 either, but pg8000.
I'm sorry man, I'd love to try this library to simplify my project :(

I'll surely look inside of it to study your approach, but for now I'll leave you a star

**Comment by 1746104160** [comment]
Psycopg is the most popular PostgreSQL database adapter for the Python programming language, so I use `psycopg2` in my code. I'll try to make my code compatible with `pg8000` in the future.
As for your problem, the simple way you can try:
```
flask-restx-marshmallow={extras= ["pandas"], version="^0.1.1"}
pg8000= "your version string"
```
Thank you for your star~

**Comment by fepe36** [comment]
> The package mysqlclient, as an optional dependency(in [pyroject.toml](https://github.com/1746104160/flask-restx-marshmallow/blob/master/pyproject.toml)) will not be installed automatically on Windows and Linux platforms.

Same issue on OpenSuse Leap 15.6 (which is a linux):

```
Collecting mysqlclient<3.0.0,>=2.1.1 (from flask-restx-marshmallow)
  Using cached mysqlclient-2.2.7.tar.gz (91 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 1.
      Trying pkg-config --exists perconaserverclient
      Command 'pkg-config --exists perconaserverclient' returned non-zero exit status 1.
      <stacktrace>
      ...
      </stacktrace>
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
```
```
$ pip --version
pip 25.1.1 from <venv>/pip (python 3.11)
```

**Comment by 1746104160** [comment]
> OpenSuse Leap

you can refer to `https://pkgs.org/download/libmysqlclient-devel` and get system dev dependencie.
